apiVersion: apps/v1
kind: Deployment
metadata:
  name: jstunnel-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jstunnel-server
  template:
    metadata:
      labels:
        app: jstunnel-server
    spec:
      containers:
        - name: jstunnel-server-container
          image: svtslv/jstunnel
          command: ["jstunnel-server"]
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: jstunnel-server-service
spec:
  type: ClusterIP
  selector:
    app: jstunnel-server
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000