# apiVersion: v1
# kind: Namespace
# metadata:
#   name: jstunnel-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jstunnel-server-deployment
  namespace: jstunnel-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jstunnel-server
  template:
    metadata:
      labels:
        app: jstunnel-server
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: jstunnel-server-container
          image: svtslv/jstunnel
          command: ['jstunnel-server', '--maxBytes=99000000000']
          tty: true
          stdin: true
          ports:
            - containerPort: 9000
          env:
            - name: TUNNEL_SERVER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: jstunnel-envs
                  key: TUNNEL_SERVER_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: jstunnel-server-service
  namespace: jstunnel-ns
spec:
  type: ClusterIP
  selector:
    app: jstunnel-server
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: jstunnel-server-middleware
  namespace: jstunnel-ns
spec:
  headers:
    customResponseHeaders:
      X-Powered-By: 'JsTunnel'
      Strict-Transport-Security: 'max-age=0; includeSubDomains'
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wildcard.jstunnel.com-ingress
  namespace: jstunnel-ns
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: jstunnel-ns-jstunnel-server-middleware@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - '*.jstunnel.com'
      secretName: wildcard.jstunnel.com-tls
  rules:
    - host: '*.jstunnel.com'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jstunnel-server-service
                port:
                  number: 9000
