#apiVersion: v1
#kind: Namespace
#metadata:
#  name: jstunnel
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jstunnel-website-deployment
  namespace: jstunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jstunnel-website
  template:
    metadata:
      labels:
        app: jstunnel-website
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: jstunnel-website-container
          image: svtslv/jstunnel
          command: ["node", "./dist/core/website/website-cli.js"]
          ports:
            - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: jstunnel-website-service
  namespace: jstunnel
spec:
  type: ClusterIP
  selector:
    app: jstunnel-website
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jstunnel.com-ingress
  namespace: jstunnel
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Powered-By: JsTunnel";
      more_set_headers "Strict-Transport-Security: max-age=0; includeSubDomains";
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - jstunnel.com
      secretName: jstunnel.com-tls
  rules:
    - host: jstunnel.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jstunnel-website-service
                port:
                  number: 9080